Updated workflow and app

diff --git a/.github/workflows/repo_dispatch.yml b/.github/workflows/repo_dispatch.yml
--- a/.github/workflows/repo_dispatch.yml
+++ b/.github/workflows/repo_dispatch.yml
@@ -37,7 +37,7 @@ jobs:
       id: "ExecuteMigrations"
       continue-on-error: true
       run: |
-        . <({ err=$({ out=$(dotnet run ${{ github.event.client_payload.environment }} ${{ github.event.client_payload.databaseName }} ${{ github.event.client_payload.throwException }}); ret=$?; } 2>&1; declare -p out ret >&2); declare -p err; } 2>&1)
+        . <({ err=$({ out=$(dotnet run ${{ github.event.client_payload.environment }} ${{ github.event.client_payload.databaseName }} }}); ret=$?; } 2>&1; declare -p out ret >&2); declare -p err; } 2>&1)
         echo "Output : ${out}"
         echo "Error: ${err}"
         echo MIGRATIONS_RUN_ERROR=${err} >> $GITHUB_OUTPUT
@@ -65,5 +65,5 @@ jobs:
       with:
         url: ${{ secrets.IntegrationApiMigrationCallbackEndpoint }}
         method: 'POST'
-        data: '{"migrationRunResult": "${{ steps.ExecuteMigrations.outcome }}", "error": "${{ steps.ExecuteMigrations.outputs.MIGRATIONS_RUN_ERROR }}"}'
+        data: '{"migrationRunResult": "${{ steps.ExecuteMigrations.outcome }}", "tenantDetails": "${{ github.event.client_payload.environment }}", error": "${{ steps.ExecuteMigrations.outputs.MIGRATIONS_RUN_ERROR }}"}'
         bearerToken: ${{ fromJson(steps.BearerTokenRequest.outputs.response).access_token }}
